contents/urls.py
from django.urls import path
from . import views
urlpatterns=[

  path("about/",views.about,name="about"),
  path("bounty/",views.bounty,name="bounty"),

    
]

faq/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path("faq/",views.index_faq,name="faq"),
    path('POP/',views.proof,name="pop"),
    ]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from . import views
from django.contrib.auth import views as auth_views
from account.views import CustomLoginView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _





urlpatterns = [
    path('',views.index,name="home"),
    path('admin_dashboard/',views.admin_dashboard,name="admin_dashboard"),
    path('pending_deposit/<int:id>/',views.admin_detail,name="admin_detail"),
    path('pending_withdrawal/<int:id>/',views.pending_withdrawal,name="pending_withdrawal"),
    path('profit/',views.investor_earnings,name="profit"),
    path('profit/add/<int:id>/',views.add_profit,name="add"),
    path('reset/',views.reset,name="reset"),
    path('reset/<int:id>/',views.reset_detail,name="reset_detail"),
    
    
    path(_('admin/'), admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('account.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('',include('contents.urls')),
    path('',include("faq.urls")),
    path('contact/',include("contact.urls")),
    
   
    



    path('accounts/login',CustomLoginView.as_view(),name="login"),
 
    path('accounts/change-password/',auth_views.PasswordChangeView.as_view(),name="password_change" ),
    path('accounts/password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
    



   #path('currencies/', include('currencies.urls')),

    
] + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns +=  i18n_patterns(
    path('',views.index,name="home"),
    path('admin_dashboard/',views.admin_dashboard,name="admin_dashboard"),
    path('pending_deposit/<int:id>/',views.admin_detail,name="admin_detail"),
    path('pending_withdrawal/<int:id>/',views.pending_withdrawal,name="pending_withdrawal"),
    path('profit/',views.investor_earnings,name="profit"),
    path('profit/add/<int:id>/',views.add_profit,name="add"),
    path('reset/',views.reset,name="reset"),
    path('reset/<int:id>/',views.reset_detail,name="reset_detail"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('account.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('',include('contents.urls')),
    path('',include("faq.urls")),
    path('contact/',include("contact.urls")),
    path('accounts/login',CustomLoginView.as_view(),name="login"),
    path('accounts/change-password/',auth_views.PasswordChangeView.as_view(),name="password_change" ),
    path('accounts/password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]








#path('api-auth/', include('rest_framework.urls')),
    #path('accounts/users/',include("account.api.urls")),
#path('accounts/login/', auth_views.LoginView.as_view(template_name="registration/login.html")),

contents/models.py
from contextlib import nullcontext
from distutils.command.upload import upload
from django.db import models


# Create your models here.
class About(models.Model):
    title=models.CharField(max_length=300)
    image=models.ImageField(upload_to="images/",blank=True,null=True)
    content=models.TextField()

    def __str__(self):
        return self.title

class Bounty(models.Model):
    heading=models.CharField(max_length=200)
    sub_heading=models.CharField(max_length=200)
    my_class=models.CharField(max_length=100,blank=True,null=True)
    background_color=models.CharField(max_length=200,blank=True,null=True)


    def __str__(self):
        return self.heading

class Reward(models.Model):
    bounty=models.ForeignKey(Bounty,on_delete=models.CASCADE)
    requirements=models.CharField(max_length=300)
    reward=models.CharField(max_length=200,blank=True,null=True)


    def __str__(self):
        return self.requirements


class Plan(models.Model):
    plan_type=models.CharField(max_length=200)
    
    plan=models.CharField(max_length=200,null=True,blank=True)
    roi=models.PositiveIntegerField(blank=True,null=True)
    Duration=models.CharField(max_length=200,blank=True,null=True)
    Referral=models.IntegerField(null=True,blank=True)
    min_deposit=models.PositiveIntegerField(null=True,blank=True)
    max_deposit=models.PositiveIntegerField(null=True,blank=True)
    withdrawal_period=models.CharField(max_length=300,null=True,blank=False)



    def __str__(self):
        return self.plan


class Crypto_logo(models.Model):
    title=models.CharField(max_length=200)
    svg=models.FileField(upload_to="images/",blank=True,null=True)

    def __str__(self):
        return self.title




class Feedback(models.Model):
    name=models.CharField(max_length=150)
    image=models.ImageField(upload_to="images/")
    testimony=models.TextField(max_length=250)
    country=models.CharField(max_length=250)

    def __str__(self):

        return self.name

contents/views.py
from django.http import HttpResponse
from django.shortcuts import render,get_object_or_404
from .models import About,Plan,Bounty


def about(request):
    about =About.objects.all()[:1]
    plans= Plan.objects.all()
    title="About Us"
    template_name="contents/about.html"
    context={"about":about,"plans":plans,"title":title}
    return render(request,template_name,context)


def bounty(request):
    bounties=Bounty.objects.all()
    template_name="contents/bounty.html"
    title="Bounty"
    context={'title':title,"bounties":bounties}
    return render(request,template_name,context)
   




contents/templates/contents/about.html
{% extends 'homepage.html' %}
{% load static %}

{% block carousel %}

{% endblock %}

{% block center %}

<div class="ui vertical stripe segment bg-dark">
    <div class="ui middle aligned stackable grid container">
      <div class="row">
        {% for obj in about %}
        <h3 class="ui header text-white">About Us</h3>
        <div class="eight wide column">
       
          <h3 class="site text-white">ACMETRADINGBOT.COM</h3>
          {% autoescape off %}
          <p class="text-white carousel-p">{{obj.content}}</p>
        {% endautoescape %}
         
        <div class="table-responsive">
          <table class="table table-striped table-dark">
            <caption>We accept
              Bitcoin, Ethereum,BNB,Bsc,usdt trc20,Litecoin, Doge, Solana, Bitcoin cash, Perfect Money</caption>

            <thead>
              <tr>
                <th scope="col">Plan</th>
                <th scope="col">Details</th>
                
              </tr>
            </thead>
            <tbody>
              {% for plan in plans %}
              <tr>
                <th scope="row">{{plan.plan}}</th>
                <td>
                  <table class="table table-responsive table-bordered  table-dark table-striped table-hover">
                    <h4 class="fw-bolder text-uppercase">{{plan.plan_type}}</h4>
          <tr>
            <td>Roi</td>
            <td>{{plan.roi}}% Daily</td>
          </tr>
          
          
          <tr>
            <td>Duration</td>
            <td>{{plan.Duration}}</td>
          </tr>
          
          
          <tr>
            <td>Referral bonus</td>
            <td>{{plan.Referral}}%</td>
          </tr>
          
          
          <tr>
            <td>Minimum</td>
            <td>${{plan.min_deposit}}</td>
          </tr>
          
          
          <tr>
            <td>Maximum</td>
            <td>${{plan.max_deposit}}</td>
          </tr>

            
          <tr>
            <td>Withdrawal Period</td>
            <td>{{plan.withdrawal_period}}</td>
          </tr>
                  </table>
                </td>
              </tr>
              
            {% endfor %}
            </tbody>
          </table>
         </div>
        </div>
        <div class="six wide right floated column">
          <img src="{{obj.image.url}}" class="ui large bordered rounded image">
        </div>

        {% endfor %}
      </div>
     
    </div>
  </div>

{% endblock %}
{% block stats %}

{% endblock %}


{% block security %}

{% endblock %}

{% block investment %}


{% endblock %}

{% block withdrawals %}

{% endblock %}

contents/templates/contents/bounty.html
{% extends 'homepage.html' %}
{% load static %}

{% block carousel %}


{% endblock %}

{% block center %}

<div class="container-fluid bg-dark p-5">

<div class="container-fluid mt-5 bg-dark">
    <h3 class="ui header text-center text-white fs-4"> BOUNTY <b class="lead text-success fs-4">PROGRAM<b> </h3>
        <p><b class="text-white">It requires just some of your free time to complete a small task and earn up to 0.5 BTC.</b></p>
        </div>

<div class="container mt-5 bg-dark">
    <p class="text-white">For validating entries and submissions for our bounty campaign, we will need to verify that all steps have been followed as we required in each one of our Forms, and somehow helps with adding value to ultimatewealth.org
        In order to filter spammy submissions we will only consider submissions from trustworty members, want to become one? Read below.</p>
        <h1 class="text-success">BECOME A TRUSTWORTHY MEMBER - DO AT LEAST (2).</h1>
        <ul type="none">
            <li class="text-white fs-6">Create your account in ultimatewealth.org <a class="text-decoration-none" href="https://epenetus.herokuapp.com/accounts/signup">https://epenetus.herokuapp.com/acccounts/signup</a></li>
            <li class="text-white fs-6">Don't do a submission if you haven't followed the rules.</li>
        </ul>
</div>

<div class="container mt-5">






    {% for bounty in bounties %}








<div class="parent mt-5">

    <div class="child-one {{bounty.my_class}}" style="background:{{bounty.background_color}};"> <h2 class="text-white p-3">{{bounty.heading}}</h2>

        <p class="fs-6 fw-bolder">{{bounty.sub_heading}}</p>
   
    </div>

    <div class="child-two">
        <ul class="pt-3">
            {% for rewards in bounty.reward_set.all %}
        <li class="fs-6 lh-lg">{{rewards.requirements}}</li>
        {% endfor %}

        </ul>


    </div>
</div>




{% endfor %}














</div>





</div>

{% endblock %}

{% block stats %}

{% endblock %}
{% block security %}

{% endblock %}
 

{% block investment %}

{% endblock %}

{% block withdrawals %}

{% endblock %}

contents/templates/contents/contents.html
{% extends 'base.html' %}
{% load static %}

{% block carosuel %}

{% endblock %}



 {% block content %}
 <div class="row">
     <div class="col-md-8">
 <div class="card">
     <div class="card-body">
        <h5 class="card-title">{{article.title|title}}</h5>
        <img src={{article.images.url}} alt="" width="100%">
        <p class="card-text mt-5">{{article.content}}</p>
     </div>
 </div>
</div></div>

  {% endblock %}